### ISSUE TITLE
Cannot get Library to work

### ISSUE THREAD

**Issue by jaden210** [extend-chrome/clipboard#13]
I very well may be missing something, But this is designed to be added to the background.ts file correct? I have followed the instructions and am not getting any errors, but can't get it to log anything back to me to know that it is working. I can attach my entire project, it is basically just an angular project shell with this in the background script. To run you can grab the /dist and load it in the extensions.

[copyclip.zip](https://github.com/extend-chrome/clipboard/files/6206716/copyclip.zip)

**Comment by jacksteamdev** [comment]
@jaden210 Your example is working for me! :+1: 

It shows the console logs in the background console:

![image](https://user-images.githubusercontent.com/23390212/113156110-4da0bd80-91ff-11eb-849d-86c98fe9509a.png)

![image](https://user-images.githubusercontent.com/23390212/113156159-5a251600-91ff-11eb-9da0-f58cacc0fbbe.png)

**Comment by jaden210** [comment]
It does get hit on init of the extension, but It doesn't seem to have a listener for any future copy commands. Is it not intended to do that?

**Comment by jacksteamdev** [comment]
This library just makes it easier to use the clipboard in a Chrome extension. :wink: 

You'll still need to use some type of event listener to read or write to the clipboard. For example, when someone clicks the browser action (extension icon):

```javascript
import { clipboard } from '@extend-chrome/clipboard'

chrome.browserAction.onClicked.addListener(async () => {
  // Write text to the clipboard, or "copy"
  clipboard.writeText('write this to the clipboard').then((text) => {
    console.log(text, 'was written to the clipboard')
  })
})
```
